CREATE TABLE IF NOT EXISTS settings (
  id                         TINYINT PRIMARY KEY DEFAULT 1,
  tir_min                    INT DEFAULT 70,
  tir_max                    INT DEFAULT 180,
  red_under                  INT DEFAULT 55,
  red_over                   INT DEFAULT 250,
  rapid_duration            INT DEFAULT 3,
  slow_duration             INT DEFAULT 24,
  carb_duration             INT DEFAULT 4,
  insulin_sensitivity       INT DEFAULT 60,
  carb_ratio                INT DEFAULT 15,
  quick_insulin_1           INT DEFAULT 1,
  quick_insulin_2           INT DEFAULT 2,
  quick_carb_1              INT DEFAULT 10,
  quick_carb_2              INT DEFAULT 20,
  telegram_enabled          BOOLEAN DEFAULT FALSE,
  telegram_high_low_alerts  BOOLEAN DEFAULT TRUE,
  telegram_prediction_alerts BOOLEAN DEFAULT TRUE,
  telegram_insulin_alerts   BOOLEAN DEFAULT FALSE,
  telegram_carb_alerts      BOOLEAN DEFAULT FALSE,
  telegram_daily_summary    BOOLEAN DEFAULT FALSE,
  telegram_daily_summary_time VARCHAR(5) DEFAULT '21:00'
);
