INSERT INTO diet_foods (name, carbs_per_100g, category) VALUES
  ('Pasta', 70, 'primi'),
  ('Riso', 80, 'primi'),
  ('Pane', 50, 'contorni'),
  ('Pesca', 9, 'frutta'),
  ('Gnocchi di patate', 30, 'primi'),
  ('Cous cous', 73, 'primi'),
  ('Farro', 67, 'primi'),
  ('Orzo', 73, 'primi'),
  ('Quinoa', 64, 'primi'),
  ('Avena', 60, 'primi'),
  ('Patate', 17, 'primi'),
  ('Patate dolci', 20, 'primi'),
  ('Lasagne', 25, 'primi'),
  ('Ravioli', 30, 'primi'),
  ('Tortellini', 35, 'primi'),
  ('Prosciutto cotto', 1, 'secondi'),
  ('Prosciutto crudo', 1, 'secondi'),
  ('Mortadella', 1, 'secondi'),
  ('Salsiccia', 2, 'secondi'),
  ('Hamburger', 2, 'secondi'),
  ('Polpette', 5, 'secondi'),
  ('Wurstel', 3, 'secondi'),
  ('Carote', 10, 'contorni'),
  ('Piselli', 14, 'contorni'),
  ('Mais', 19, 'contorni'),
  ('Zucca', 7, 'contorni'),
  ('Cipolle', 9, 'contorni'),
  ('Pomodori', 4, 'contorni'),
  ('Zucchine', 3, 'contorni'),
  ('Melanzane', 6, 'contorni'),
  ('Peperoni', 6, 'contorni'),
  ('Broccoli', 4, 'contorni'),
  ('Cavolfiore', 5, 'contorni'),
  ('Fagiolini', 4, 'contorni'),
  ('Funghi', 2, 'contorni'),
  ('Mela', 14, 'frutta'),
  ('Pera', 15, 'frutta'),
  ('Banana', 23, 'frutta'),
  ('Albicocca', 11, 'frutta'),
  ('Arancia', 12, 'frutta'),
  ('Mandarino', 13, 'frutta'),
  ('Kiwi', 15, 'frutta'),
  ('Fragole', 8, 'frutta'),
  ('Ciliegie', 16, 'frutta'),
  ('Uva', 18, 'frutta'),
  ('Anguria', 8, 'frutta'),
  ('Melone', 8, 'frutta'),
  ('Ananas', 13, 'frutta'),
  ('Mango', 15, 'frutta'),
  ('Latte intero', 5, 'latticini'),
  ('Latte scremato', 5, 'latticini'),
  ('Yogurt bianco', 5, 'latticini'),
  ('Yogurt alla frutta', 15, 'latticini'),
  ('Yogurt greco', 4, 'latticini'),
  ('Mozzarella', 1, 'latticini'),
  ('Ricotta', 3, 'latticini'),
  ('Formaggio spalmabile', 4, 'latticini'),
  ('Budino', 15, 'latticini'),
  ('Succo di frutta', 11, 'bevande'),
  ('Coca Cola', 11, 'bevande'),
  ('Aranciata', 10, 'bevande'),
  ('Tè zuccherato', 8, 'bevande'),
  ('Latte e cacao', 12, 'bevande'),
  ('Frullato di frutta', 15, 'bevande'),
  ('Pizza margherita', 30, 'prodotti_da_forno'),
  ('Focaccia', 50, 'prodotti_da_forno'),
  ('Piadina', 55, 'prodotti_da_forno'),
  ('Cracker', 65, 'prodotti_da_forno'),
  ('Grissini', 70, 'prodotti_da_forno'),
  ('Biscotti secchi', 73, 'prodotti_da_forno'),
  ('Cornetto', 50, 'prodotti_da_forno'),
  ('Panino', 55, 'prodotti_da_forno'),
  ('Crostata', 45, 'prodotti_da_forno')
ON DUPLICATE KEY UPDATE
  carbs_per_100g = VALUES(carbs_per_100g),
  category = VALUES(category);
